if gastar_pouco and viagem_curta then viagemTrabalho.
if gastar_pouco and viagem_longa then viagemGastarPoucoLonga.
%__GASTAR MUITO__
if gastar_muito and viagem_longa then viagemPasseio.
if gastar_muito and viagem_curta then viagemGastarMuitoCurta.

if casa_de_banho and zona_fumador then casaBanhoFumador.
if casa_de_banho and sem_zona_fumador then casaBanhoSemZonaFumador.

if sem_casa_de_banho and zona_fumador then semCasaBanhoFumador.
if sem_casa_de_banho and sem_zona_fumador then semCasaBanhoSemZonaFumador.


if wifi and mais_ecologico then wifiMaisEcologico.
if sem_wifi and mais_ecologico then semWifiMaisEcologico.

if wifi and menos_ecologico then wifiMenosEcologico.
if sem_wifi and menos_ecologico then semWifiMenosEcologico.


%Junção de Perguntas Intermédio%
if viagemTrabalho and casaBanhoFumador then viagemTrabalhoCasaBanhoFumador.
if viagemTrabalho and casaBanhoSemZonaFumador then viagemTrabalhoCasaBanhoSemZonaFumador.
if viagemTrabalho and semCasaBanhoFumador then viagemTrabalhoSemCasaBanhoFumador.
if viagemTrabalho and semCasaBanhoSemZonaFumador then viagemTrabalhoSemCasaBanhoSemZonaFumador.
if viagemGastarPoucoLonga and casaBanhoFumador then viagemGastarPoucoLongaCasaBanhoFumador.
if viagemGastarPoucoLonga and casaBanhoSemZonaFumador then viagemGastarPoucoLongaCasaBanhoSemZonaFumador.
if viagemGastarPoucoLonga and semCasaBanhoFumador then viagemGastarPoucoLongaSemCasaBanhoFumador.
if viagemGastarPoucoLonga and semCasaBanhoSemZonaFumador then viagemGastarPoucoLongaSemCasaBanhoSemZonaFumador.

if viagemPasseio and casaBanhoFumador then viagemPasseioCasaBanhoFumador.
if viagemPasseio and casaBanhoSemZonaFumador then viagemPasseioCasaBanhoSemZonaFumador.
if viagemPasseio and semCasaBanhoFumador then viagemPasseioSemCasaBanhoFumador.
if viagemPasseio and semCasaBanhoSemZonaFumador then viagemPasseioSemCasaBanhoSemZonaFumador.

if viagemGastarMuitoCurta and casaBanhoFumador then viagemGastarMuitoCurtaCasaBanhoFumador.
if viagemGastarMuitoCurta and casaBanhoSemZonaFumador then viagemGastarMuitoCurtaCasaBanhoSemZonaFumador.
if viagemGastarMuitoCurta and semCasaBanhoFumador then viagemGastarMuitoCurtaSemCasaBanhoFumador.
if viagemGastarMuitoCurta and semCasaBanhoSemZonaFumador then viagemGastarMuitoCurtaSemCasaBanhoSemZonaFumador.



%FINAIS %
if viagemTrabalhoCasaBanhoFumador and wifiMaisEcologico then final:trabalhoCasaBanhoFumadorWifiEcologico.
if viagemTrabalhoCasaBanhoFumador and semWifiMaisEcologico then final:trabalhoCasaBanhoFumadorSemWifiEcologico.
if viagemTrabalhoCasaBanhoFumador and wifiMenosEcologico then final:trabalhoCasaBanhoFumadorWifiMenosEcologico.
if viagemTrabalhoCasaBanhoFumador and semWifiMenosEcologico then final:trabalhoCasaBanhoFumadorSemWifiMenosEcologico.

if viagemTrabalhoCasaBanhoSemZonaFumador and wifiMaisEcologico then final:trabalhoCasaBanhoNaoFumadorWifiEcologico.
if viagemTrabalhoCasaBanhoSemZonaFumador and semWifiMaisEcologico then final:trabalhoCasaBanhoNaoFumadorSemWifiEcologico.
if viagemTrabalhoCasaBanhoSemZonaFumador and wifiMenosEcologico then final:trabalhoCasaBanhoNaoFumadorWifiMenosEcologico.
if viagemTrabalhoCasaBanhoSemZonaFumador and semWifiMenosEcologico then final:trabalhoCasaBanhoNaoFumadorSemWifiMenosEcologico.

if viagemTrabalhoSemCasaBanhoFumador and wifiMaisEcologico then final:trabalhoSemCasaBanhoFumadorWifiEcologico.
if viagemTrabalhoSemCasaBanhoFumador and semWifiMaisEcologico then final:trabalhoSemCasaBanhoFumadorSemWifiEcologico.
if viagemTrabalhoSemCasaBanhoFumador and wifiMenosEcologico then final:trabalhoSemCasaBanhoFumadorWifiMenosEcologico.
if viagemTrabalhoSemCasaBanhoFumador and semWifiMenosEcologico then final:trabalhoSemCasaBanhoFumadorSemWifiMenosEcologico.

if viagemTrabalhoSemCasaBanhoSemZonaFumador and wifiMaisEcologico then final:trabalhoSemCasaBanhoNaoFumadorWifiEcologico.
if viagemTrabalhoSemCasaBanhoSemZonaFumador and semWifiMaisEcologico then final:trabalhoSemCasaBanhoNaoFumadorSemWifiEcologico.
if viagemTrabalhoSemCasaBanhoSemZonaFumador and wifiMenosEcologico then final:trabalhoSemCasaBanhoNaoFumadorWifiMenosEcologico.
if viagemTrabalhoSemCasaBanhoSemZonaFumador and semWifiMenosEcologico then final:trabalhoSemCasaBanhoNaoFumadorSemWifiMenosEcologico.

if viagemGastarPoucoLongaCasaBanhoFumador and wifiMaisEcologico then final:gastarPoucoLongaCasaBanhoFumadorWifiEcologico.
if viagemGastarPoucoLongaCasaBanhoFumador and semWifiMaisEcologico then final:gastarPoucoLongaCasaBanhoFumadorSemWifiEcologico.
if viagemGastarPoucoLongaCasaBanhoFumador and wifiMenosEcologico then final:gastarPoucoLongaCasaBanhoFumadorWifiMenosEcologico.
if viagemGastarPoucoLongaCasaBanhoFumador and semWifiMenosEcologico then final:gastarPoucoLongaCasaBanhoFumadorSemWifiMenosEcologico.

if viagemGastarPoucoLongaCasaBanhoSemZonaFumador and wifiMaisEcologico then final:gastarPoucoLongaCasaBanhoNaoFumadorWifiEcologico.
if viagemGastarPoucoLongaCasaBanhoSemZonaFumador and semWifiMaisEcologico then final:gastarPoucoLongaCasaBanhoNaoFumadorSemWifiEcologico.
if viagemGastarPoucoLongaCasaBanhoSemZonaFumador and wifiMenosEcologico then final:gastarPoucoLongaCasaBanhoNaoFumadorWifiMenosEcologico.
if viagemGastarPoucoLongaCasaBanhoSemZonaFumador and semWifiMenosEcologico then final:gastarPoucoLongaCasaBanhoNaoFumadorSemWifiMenosEcologico.

if viagemGastarPoucoLongaSemCasaBanhoFumador and wifiMaisEcologico then final:gastarPoucoLongaSemCasaBanhoFumadorWifiEcologico.
if viagemGastarPoucoLongaSemCasaBanhoFumador and semWifiMaisEcologico then final:gastarPoucoLongaSemCasaBanhoFumadorSemWifiEcologico.
if viagemGastarPoucoLongaSemCasaBanhoFumador and wifiMenosEcologico then final:gastarPoucoLongaSemCasaBanhoFumadorWifiMenosEcologico.
if viagemGastarPoucoLongaSemCasaBanhoFumador and semWifiMenosEcologico then final:gastarPoucoLongaSemCasaBanhoFumadorSemWifiMenosEcologico.

if viagemGastarPoucoLongaSemCasaBanhoSemZonaFumador and wifiMaisEcologico then final:gastarPoucoLongaSemCasaBanhoNaoFumadorWifiEcologico.
if viagemGastarPoucoLongaSemCasaBanhoSemZonaFumador and semWifiMaisEcologico then final:gastarPoucoLongaSemCasaBanhoNaoFumadorSemWifiEcologico.
if viagemGastarPoucoLongaSemCasaBanhoSemZonaFumador and wifiMenosEcologico then final:gastarPoucoLongaSemCasaBanhoNaoFumadorWifiMenosEcologico.
if viagemGastarPoucoLongaSemCasaBanhoSemZonaFumador and semWifiMenosEcologico then final:gastarPoucoLongaSemCasaBanhoNaoFumadorSemWifiMenosEcologico.

if viagemPasseioCasaBanhoFumador and wifiMaisEcologico then final:passeioCasaBanhoFumadorWifiEcologico.
if viagemPasseioCasaBanhoFumador and semWifiMaisEcologico then final:passeioCasaBanhoFumadorSemWifiEcologico.
if viagemPasseioCasaBanhoFumador and wifiMenosEcologico then final:passeioCasaBanhoFumadorWifiMenosEcologico.
if viagemPasseioCasaBanhoFumador and semWifiMenosEcologico then final:passeioCasaBanhoFumadorSemWifiMenosEcologico.

if viagemPasseioCasaBanhoSemZonaFumador and wifiMaisEcologico then final:passeioCasaBanhoNaoFumadorWifiEcologico.
if viagemPasseioCasaBanhoSemZonaFumador and semWifiMaisEcologico then final:passeioCasaBanhoNaoFumadorSemWifiEcologico.
if viagemPasseioCasaBanhoSemZonaFumador and wifiMenosEcologico then final:passeioCasaBanhoNaoFumadorWifiMenosEcologico.
if viagemPasseioCasaBanhoSemZonaFumador and semWifiMenosEcologico then final:passeioCasaBanhoNaoFumadorSemWifiMenosEcologico.

if viagemPasseioSemCasaBanhoFumador and wifiMaisEcologico then final:passeioSemCasaBanhoFumadorWifiEcologico.
if viagemPasseioSemCasaBanhoFumador and semWifiMaisEcologico then final:passeioSemCasaBanhoFumadorSemWifiEcologico.
if viagemPasseioSemCasaBanhoFumador and wifiMenosEcologico then final:passeioSemCasaBanhoFumadorWifiMenosEcologico.
if viagemPasseioSemCasaBanhoFumador and semWifiMenosEcologico then final:passeioSemCasaBanhoFumadorSemWifiMenosEcologico.

if viagemPasseioSemCasaBanhoSemZonaFumador and wifiMaisEcologico then final:passeioSemCasaBanhoNaoFumadorWifiEcologico.
if viagemPasseioSemCasaBanhoSemZonaFumador and semWifiMaisEcologico then final:passeioSemCasaBanhoNaoFumadorSemWifiEcologico.
if viagemPasseioSemCasaBanhoSemZonaFumador and wifiMenosEcologico then final:passeioSemCasaBanhoNaoFumadorWifiMenosEcologico.
if viagemPasseioSemCasaBanhoSemZonaFumador and semWifiMenosEcologico then final:passeioSemCasaBanhoNaoFumadorSemWifiMenosEcologico.

if viagemGastarMuitoCurtaCasaBanhoFumador and wifiMaisEcologico then final:gastarMuitoCurtaCasaBanhoFumadorWifiEcologico.
if viagemGastarMuitoCurtaCasaBanhoFumador and semWifiMaisEcologico then final:gastarMuitoCurtaCasaBanhoFumadorSemWifiEcologico.
if viagemGastarMuitoCurtaCasaBanhoFumador and wifiMenosEcologico then final:gastarMuitoCurtaCasaBanhoFumadorWifiMenosEcologico.
if viagemGastarMuitoCurtaCasaBanhoFumador and semWifiMenosEcologico then final:gastarMuitoCurtaCasaBanhoFumadorSemWifiMenosEcologico.

if viagemGastarMuitoCurtaCasaBanhoSemZonaFumador and wifiMaisEcologico then final:gastarMuitoCurtaCasaBanhoSemZonaFumadorWifiEcologico.
if viagemGastarMuitoCurtaCasaBanhoSemZonaFumador and semWifiMaisEcologico then final:gastarMuitoCurtaCasaBanhoSemZonaFumadorSemWifiEcologico.
if viagemGastarMuitoCurtaCasaBanhoSemZonaFumador and wifiMenosEcologico then final:gastarMuitoCurtaCasaBanhoSemZonaFumadorWifiMenosEcologico.
if viagemGastarMuitoCurtaCasaBanhoSemZonaFumador and semWifiMenosEcologico then final:gastarMuitoCurtaCasaBanhoSemZonaFumadorSemWifiMenosEcologico.

if viagemGastarMuitoCurtaSemCasaBanhoFumador and wifiMaisEcologico then final:gastarMuitoCurtaSemCasaBanhoFumadorWifiEcologico.
if viagemGastarMuitoCurtaSemCasaBanhoFumador and semWifiMaisEcologico then final:gastarMuitoCurtaSemCasaBanhoFumadorSemWifiEcologico.
if viagemGastarMuitoCurtaSemCasaBanhoFumador and wifiMenosEcologico then final:gastarMuitoCurtaSemCasaBanhoFumadorWifiMenosEcologico.
if viagemGastarMuitoCurtaSemCasaBanhoFumador and semWifiMenosEcologico then final:gastarMuitoCurtaSemCasaBanhoFumadorSemWifiMenosEcologico.

if viagemGastarMuitoCurtaSemCasaBanhoSemZonaFumador and wifiMaisEcologico then final:gastarMuitoCurtaSemCasaBanhoSemZonaFumadorWifiEcologico.
if viagemGastarMuitoCurtaSemCasaBanhoSemZonaFumador and semWifiMaisEcologico then final:gastarMuitoCurtaSemCasaBanhoSemZonaFumadorSemWifiEcologico.
if viagemGastarMuitoCurtaSemCasaBanhoSemZonaFumador and wifiMenosEcologico then final:gastarMuitoCurtaSemCasaBanhoSemZonaFumadorWifiMenosEcologico.
if viagemGastarMuitoCurtaSemCasaBanhoSemZonaFumador and semWifiMenosEcologico then final:gastarMuitoCurtaSemCasaBanhoSemZonaFumadorSemWifiMenosEcologico.