if origem_braga and destino_porto and gastar_pouco and viagem_curta then perfil1.
if origem_braga and destino_porto and gastar_pouco and sem_restricao then perfil2.
if origem_braga and destino_porto and gastar_pouco and viagem_longa then perfil3.
if origem_braga and destino_porto and sem_orcamento and viagem_curta then perfil4.
if origem_braga and destino_porto and sem_orcamento and sem_restricao then perfil5.
if origem_braga and destino_porto and sem_orcamento and viagem_longa then perfil6.
if origem_braga and destino_porto and gastar_muito and viagem_curta then perfil7.
if origem_braga and destino_porto and gastar_muito and sem_restricao then perfil8.
if origem_braga and destino_porto and gastar_muito and viagem_longa then perfil9.
if origem_porto and destino_lisboa and gastar_pouco and viagem_curta then perfil10.
if origem_porto and destino_lisboa and gastar_pouco and sem_restricao then perfil11.
if origem_porto and destino_lisboa and gastar_pouco and viagem_longa then perfil12.
if origem_porto and destino_lisboa and sem_orcamento and viagem_curta then perfil13.
if origem_porto and destino_lisboa and sem_orcamento and sem_restricao then perfil14.
if origem_porto and destino_lisboa and sem_orcamento and viagem_longa then perfil15.
if origem_porto and destino_lisboa and gastar_muito and viagem_curta then perfil16.
if origem_porto and destino_lisboa and gastar_muito and sem_restricao then perfil17.
if origem_porto and destino_lisboa and gastar_muito and viagem_longa then perfil18.
if origem_faro and destino_lisboa and gastar_pouco and viagem_curta then perfil19.
if origem_faro and destino_lisboa and gastar_pouco and sem_restricao then perfil20.
if origem_faro and destino_lisboa and gastar_pouco and viagem_longa then perfil21.
if origem_faro and destino_lisboa and sem_orcamento and viagem_curta then perfil22.
if origem_faro and destino_lisboa and sem_orcamento and sem_restricao then perfil23.
if origem_faro and destino_lisboa and sem_orcamento and viagem_longa then perfil24.
if origem_faro and destino_lisboa and gastar_muito and viagem_curta then perfil25.
if origem_faro and destino_lisboa and gastar_muito and sem_restricao then perfil26.
if origem_faro and destino_lisboa and gastar_muito and viagem_longa then perfil27.
if origem_porto and destino_viseu and gastar_pouco and viagem_curta then perfil28.
if origem_porto and destino_viseu and gastar_pouco and sem_restricao then perfil29.
if origem_porto and destino_viseu and gastar_pouco and viagem_longa then perfil30.
if origem_porto and destino_viseu and sem_orcamento and viagem_curta then perfil31.
if origem_porto and destino_viseu and sem_orcamento and sem_restricao then perfil32.
if origem_porto and destino_viseu and sem_orcamento and viagem_longa then perfil33.
if origem_porto and destino_viseu and gastar_muito and viagem_curta then perfil34.
if origem_porto and destino_viseu and gastar_muito and sem_restricao then perfil35.
if origem_porto and destino_viseu and gastar_muito and viagem_longa then perfil36.
if origem_braga and destino_guimaraes and gastar_pouco and viagem_curta then perfil37.
if origem_braga and destino_guimaraes and gastar_pouco and sem_restricao then perfil38.
if origem_braga and destino_guimaraes and gastar_pouco and viagem_longa then perfil39.
if origem_braga and destino_guimaraes and sem_orcamento and viagem_curta then perfil40.
if origem_braga and destino_guimaraes and sem_orcamento and sem_restricao then perfil41.
if origem_braga and destino_guimaraes and sem_orcamento and viagem_longa then perfil42.
if origem_braga and destino_guimaraes and gastar_muito and viagem_curta then perfil43.
if origem_braga and destino_guimaraes and gastar_muito and sem_restricao then perfil44.
if origem_braga and destino_guimaraes and gastar_muito and viagem_longa then perfil45.
if origem_guimaraes and destino_porto and gastar_pouco and viagem_curta then perfil46.
if origem_guimaraes and destino_porto and gastar_pouco and sem_restricao then perfil47.
if origem_guimaraes and destino_porto and gastar_pouco and viagem_longa then perfil48.
if origem_guimaraes and destino_porto and sem_orcamento and viagem_curta then perfil49.
if origem_guimaraes and destino_porto and sem_orcamento and sem_restricao then perfil50.
if origem_guimaraes and destino_porto and sem_orcamento and viagem_longa then perfil51.
if origem_guimaraes and destino_porto and gastar_muito and viagem_curta then perfil52.
if origem_guimaraes and destino_porto and gastar_muito and sem_restricao then perfil53.
if origem_guimaraes and destino_porto and gastar_muito and viagem_longa then perfil54.
%VERIFICAR
if origem_coimbra and destino_viseu and gastar_pouco and viagem_curta then perfil55.
if origem_coimbra and destino_viseu and gastar_pouco and sem_restricao then perfil56.
if origem_coimbra and destino_viseu and gastar_pouco and viagem_longa then perfil57.
if origem_coimbra and destino_viseu and sem_orcamento and viagem_curta then perfil58.
if origem_coimbra and destino_viseu and sem_orcamento and sem_restricao then perfil59.
if origem_coimbra and destino_viseu and sem_orcamento and viagem_longa then perfil60.
if origem_coimbra and destino_viseu and gastar_muito and viagem_curta then perfil61.
if origem_coimbra and destino_viseu and gastar_muito and sem_restricao then perfil62.
if origem_coimbra and destino_viseu and gastar_muito and viagem_longa then perfil63.
%VERIFICAR
if origem_braga and destino_coimbra and gastar_pouco and viagem_curta then perfil64.
if origem_braga and destino_coimbra and gastar_pouco and sem_restricao then perfil65.
if origem_braga and destino_coimbra and gastar_pouco and viagem_longa then perfil66.
if origem_braga and destino_coimbra and sem_orcamento and viagem_curta then perfil67.
if origem_braga and destino_coimbra and sem_orcamento and sem_restricao then perfil68.
if origem_braga and destino_coimbra and sem_orcamento and viagem_longa then perfil69.
if origem_braga and destino_coimbra and gastar_muito and viagem_curta then perfil70.
if origem_braga and destino_coimbra and gastar_muito and sem_restricao then perfil71.
if origem_braga and destino_coimbra and gastar_muito and viagem_longa then perfil72.
%VERIFICAR
if origem_lisboa and destino_coimbra and gastar_pouco and viagem_curta then perfil73.
if origem_lisboa and destino_coimbra and gastar_pouco and sem_restricao then perfil74.
if origem_lisboa and destino_coimbra and gastar_pouco and viagem_longa then perfil75.
if origem_lisboa and destino_coimbra and sem_orcamento and viagem_curta then perfil76.
if origem_lisboa and destino_coimbra and sem_orcamento and sem_restricao then perfil77.
if origem_lisboa and destino_coimbra and sem_orcamento and viagem_longa then perfil78.
if origem_lisboa and destino_coimbra and gastar_muito and viagem_curta then perfil79.
if origem_lisboa and destino_coimbra and gastar_muito and sem_restricao then perfil80.
if origem_lisboa and destino_coimbra and gastar_muito and viagem_longa then perfil81.
%%AO CONTRARIO
if origem_porto and destino_braga and gastar_pouco and viagem_curta then perfil82.
if origem_porto and destino_braga and gastar_pouco and sem_restricao then perfil83.
if origem_porto and destino_braga and gastar_pouco and viagem_longa then perfil84.
if origem_porto and destino_braga and sem_orcamento and viagem_curta then perfil85.
if origem_porto and destino_braga and sem_orcamento and sem_restricao then perfil86.
if origem_porto and destino_braga and sem_orcamento and viagem_longa then perfil87.
if origem_porto and destino_braga and gastar_muito and viagem_curta then perfil88.
if origem_porto and destino_braga and gastar_muito and sem_restricao then perfil90.
if origem_porto and destino_braga and gastar_muito and viagem_longa then perfil91.
if origem_lisboa and destino_porto and gastar_pouco and viagem_curta then perfil92.
if origem_lisboa and destino_porto and gastar_pouco and sem_restricao then perfil93.
if origem_lisboa and destino_porto and gastar_pouco and viagem_longa then perfil94.
if origem_lisboa and destino_porto and sem_orcamento and viagem_curta then perfil95.
if origem_lisboa and destino_porto and sem_orcamento and sem_restricao then perfil96.
if origem_lisboa and destino_porto and sem_orcamento and viagem_longa then perfil97.
if origem_lisboa and destino_porto and gastar_muito and viagem_curta then perfil98.
if origem_lisboa and destino_porto and gastar_muito and sem_restricao then perfil99.
if origem_lisboa and destino_porto and gastar_muito and viagem_longa then perfil100.
if origem_lisboa and destino_daro and gastar_pouco and viagem_curta then perfil101.
if origem_lisboa and destino_daro and gastar_pouco and sem_restricao then perfil102.
if origem_lisboa and destino_daro and gastar_pouco and viagem_longa then perfil103.
if origem_lisboa and destino_daro and sem_orcamento and viagem_curta then perfil104.
if origem_lisboa and destino_daro and sem_orcamento and sem_restricao then perfil105.
if origem_lisboa and destino_daro and sem_orcamento and viagem_longa then perfil106.
if origem_lisboa and destino_daro and gastar_muito and viagem_curta then perfil107.
if origem_lisboa and destino_daro and gastar_muito and sem_restricao then perfil108.
if origem_lisboa and destino_daro and gastar_muito and viagem_longa then perfil109.
if origem_viseu and destino_porto and gastar_pouco and viagem_curta then perfil110.
if origem_viseu and destino_porto and gastar_pouco and sem_restricao then perfil111.
if origem_viseu and destino_porto and gastar_pouco and viagem_longa then perfil112.
if origem_viseu and destino_porto and sem_orcamento and viagem_curta then perfil113.
if origem_viseu and destino_porto and sem_orcamento and sem_restricao then perfil114.
if origem_viseu and destino_porto and sem_orcamento and viagem_longa then perfil115.
if origem_viseu and destino_porto and gastar_muito and viagem_curta then perfil116.
if origem_viseu and destino_porto and gastar_muito and sem_restricao then perfil117.
if origem_viseu and destino_porto and gastar_muito and viagem_longa then perfil118.
if origem_guimaraes and destino_braga and gastar_pouco and viagem_curta then perfil119.
if origem_guimaraes and destino_braga and gastar_pouco and sem_restricao then perfil120.
if origem_guimaraes and destino_braga and gastar_pouco and viagem_longa then perfil121.
if origem_guimaraes and destino_braga and sem_orcamento and viagem_curta then perfil122.
if origem_guimaraes and destino_braga and sem_orcamento and sem_restricao then perfil123.
if origem_guimaraes and destino_braga and sem_orcamento and viagem_longa then perfil124.
if origem_guimaraes and destino_braga and gastar_muito and viagem_curta then perfil125.
if origem_guimaraes and destino_braga and gastar_muito and sem_restricao then perfil126.
if origem_guimaraes and destino_braga and gastar_muito and viagem_longa then perfil127.
if origem_porto and destino_guimaraes and gastar_pouco and viagem_curta then perfil128.
if origem_porto and destino_guimaraes and gastar_pouco and sem_restricao then perfil129.
if origem_porto and destino_guimaraes and gastar_pouco and viagem_longa then perfil130.
if origem_porto and destino_guimaraes and sem_orcamento and viagem_curta then perfil131.
if origem_porto and destino_guimaraes and sem_orcamento and sem_restricao then perfil132.
if origem_porto and destino_guimaraes and sem_orcamento and viagem_longa then perfil133.
if origem_porto and destino_guimaraes and gastar_muito and viagem_curta then perfil134.
if origem_porto and destino_guimaraes and gastar_muito and sem_restricao then perfil135.
if origem_porto and destino_guimaraes and gastar_muito and viagem_longa then perfil136.
%VERIFICAR
if origem_viseu and destino_coimbra and gastar_pouco and viagem_curta then perfil137.
if origem_viseu and destino_coimbra and gastar_pouco and sem_restricao then perfil138.
if origem_viseu and destino_coimbra and gastar_pouco and viagem_longa then perfil139.
if origem_viseu and destino_coimbra and sem_orcamento and viagem_curta then perfil140.
if origem_viseu and destino_coimbra and sem_orcamento and sem_restricao then perfil141.
if origem_viseu and destino_coimbra and sem_orcamento and viagem_longa then perfil142.
if origem_viseu and destino_coimbra and gastar_muito and viagem_curta then perfil143.
if origem_viseu and destino_coimbra and gastar_muito and sem_restricao then perfil144.
if origem_viseu and destino_coimbra and gastar_muito and viagem_longa then perfil145.
%VERIFICAR
if origem_coimbra and destino_braga and gastar_pouco and viagem_curta then perfil146.
if origem_coimbra and destino_braga and gastar_pouco and sem_restricao then perfil147.
if origem_coimbra and destino_braga and gastar_pouco and viagem_longa then perfil148.
if origem_coimbra and destino_braga and sem_orcamento and viagem_curta then perfil149.
if origem_coimbra and destino_braga and sem_orcamento and sem_restricao then perfil150.
if origem_coimbra and destino_braga and sem_orcamento and viagem_longa then perfil151.
if origem_coimbra and destino_braga and gastar_muito and viagem_curta then perfil152.
if origem_coimbra and destino_braga and gastar_muito and sem_restricao then perfil153.
if origem_coimbra and destino_braga and gastar_muito and viagem_longa then perfil154.

%VERIFICAR
if origem_coimbra and destino_lisboa and gastar_pouco and viagem_curta then perfil155.
if origem_coimbra and destino_lisboa and gastar_pouco and sem_restricao then perfil156.
if origem_coimbra and destino_lisboa and gastar_pouco and viagem_longa then perfil157.
if origem_coimbra and destino_lisboa and sem_orcamento and viagem_curta then perfil158.
if origem_coimbra and destino_lisboa and sem_orcamento and sem_restricao then perfil159.
if origem_coimbra and destino_lisboa and sem_orcamento and viagem_longa then perfil160.
if origem_coimbra and destino_lisboa and gastar_muito and viagem_curta then perfil161.
if origem_coimbra and destino_lisboa and gastar_muito and sem_restricao then perfil162.
if origem_coimbra and destino_lisboa and gastar_muito and viagem_longa then perfil163.